#!/usr/bin/env python3
"""Shared scholarly quotes for calculation pad generators."""

QUOTES = [
    ("Isaac Newton", "If I have seen further, it is by standing on the shoulders of giants."),
    ("Albert Einstein", "Imagination is more important than knowledge."),
    ("Richard Feynman", "The first principle is that you must not fool yourself — and you are the easiest person to fool."),
    ("Carl Friedrich Gauss", "Mathematics is the queen of the sciences, and number theory is the queen of mathematics."),
    ("Henri Poincaré", "The scientist does not study nature because it is useful; he studies it because he delights in it."),
    ("Marie Curie", "Nothing in life is to be feared, it is only to be understood."),
    ("Galileo Galilei", "The book of nature is written in the language of mathematics."),
    ("Johannes Kepler", "I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses."),
    ("Niels Bohr", "Prediction is very difficult, especially about the future."),
    ("Werner Heisenberg", "What we observe is not nature itself, but nature exposed to our method of questioning."),
    ("Paul Dirac", "A physical law must possess mathematical beauty."),
    ("John von Neumann", "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is."),
    ("Alan Turing", "We can only see a short distance ahead, but we can see plenty there that needs to be done."),
    ("Emmy Noether", "My methods are really methods of working and thinking; this is why they have crept in everywhere anonymously."),
    ("Leonardo da Vinci", "Simplicity is the ultimate sophistication."),
    ("Archimedes", "Give me a place to stand, and I shall move the earth."),
    ("Euclid", "There is no royal road to geometry."),
    ("Gottfried Wilhelm Leibniz", "The present is big with the future."),
    ("Leonhard Euler", "Logic is the foundation of the certainty of all the knowledge we acquire."),
    ("Joseph-Louis Lagrange", "As long as algebra and geometry have been separated, their progress has been slow and their uses limited."),
    ("Pierre-Simon Laplace", "What we know is not much. What we do not know is immense."),
    ("James Clerk Maxwell", "Thoroughly conscious ignorance is the prelude to every real advance in science."),
    ("Michael Faraday", "Nothing is too wonderful to be true, if it be consistent with the laws of nature."),
    ("Ludwig Boltzmann", "If you are out to describe the truth, leave elegance to the tailor."),
    ("Erwin Schrödinger", "The task is not to see what has never been seen, but to think what has never been thought."),
    ("Max Planck", "Science cannot solve the ultimate mystery of nature. And that is because, in the last analysis, we ourselves are part of the mystery we are trying to solve."),
    ("Enrico Fermi", "There are two possible outcomes: if the result confirms the hypothesis, then you have made a measurement. If the result is contrary to the hypothesis, then you have made a discovery."),
    ("David Hilbert", "We must know. We will know."),
    ("Bernhard Riemann", "The value of mathematical science is measured by the progress it brings about in our understanding of the physical world."),
    ("Évariste Galois", "Unfortunately what is little recognized is that the most worthwhile scientific works are those in which the author points out what he does not know."),
    ("Blaise Pascal", "We are generally the better persuaded by the reasons we discover ourselves than by those given to us by others."),
    ("René Descartes", "Each problem that I solved became a rule which served afterwards to solve other problems."),
    ("Kurt Gödel", "The more I think about language, the more it amazes me that people ever understand each other at all."),
    ("Ada Lovelace", "That brain of mine is something more than merely mortal; as time will show."),
    ("Srinivasa Ramanujan", "An equation for me has no meaning unless it expresses a thought of God."),
    ("George Pólya", "If you cannot solve the proposed problem, try to solve first some related problem."),
    ("G. H. Hardy", "A mathematician, like a painter or a poet, is a maker of patterns."),
    ("John Archibald Wheeler", "If you are not completely confused by quantum mechanics, you do not understand it."),
    ("Steven Weinberg", "The effort to understand the universe is one of the very few things that lifts human life a little above the level of farce."),
    ("Roger Penrose", "Sometimes it is the people no one can imagine anything of who do the things no one can imagine."),
    ("Terence Tao", "Mathematics is a game of ideas. The more ideas you have, the richer the game becomes."),
    ("Maryam Mirzakhani", "I find it fascinating that you can look at the same problem from different perspectives and approach it using different methods."),
    ("Subrahmanyan Chandrasekhar", "Science is a perception of the world around us. Science is a place where what you find in nature pleases you."),
    ("Freeman Dyson", "The essential fact which emerges is that the three smallest and most active reservoirs of carbon are the atmosphere, the biosphere, and the human population."),
    ("Claude Shannon", "I visualize a time when we will be to robots what dogs are to humans, and I am rooting for the machines."),
    ("Norbert Wiener", "The world of the future will be an ever more demanding struggle against the limitations of our intelligence."),
    ("Grace Hopper", "The most dangerous phrase in the language is: we have always done it this way."),
    ("Dennis Ritchie", "UNIX is simple. It just takes a genius to understand its simplicity."),
    ("Donald Knuth", "The most important thing in the programming language is the name. A language will not succeed without a good name."),
    ("Edsger W. Dijkstra", "Simplicity is a great virtue but it requires hard work to achieve it and education to appreciate it."),
    ("Alan Kay", "The best way to predict the future is to invent it."),
    ("Barbara Liskov", "The power of abstraction is that it allows you to ignore the details you do not need to know."),
    ("Stephen Hawking", "Look up at the stars and not down at your feet. Try to make sense of what you see."),
    ("Carl Sagan", "Somewhere, something incredible is waiting to be known."),
    ("Neil deGrasse Tyson", "The good thing about science is that it is true whether or not you believe in it."),

    # ── Additional mathematicians & scientists ─────────────────────
    ("Albert Einstein", "We cannot solve our problems with the same thinking we used when we created them."),
    ("Albert Einstein", "The important thing is not to stop questioning. Curiosity has its own reason for existing."),
    ("Albert Einstein", "Anyone who has never made a mistake has never tried anything new."),
    ("Albert Einstein", "In the middle of difficulty lies opportunity."),
    ("Albert Einstein", "The true sign of intelligence is not knowledge but imagination."),
    ("Albert Einstein", "Education is what remains after one has forgotten what one has learned in school."),
    ("Albert Einstein", "Everything should be made as simple as possible, but not simpler."),
    ("Albert Einstein", "Great spirits have always encountered violent opposition from mediocre minds."),
    ("Isaac Newton", "No great discovery was ever made without a bold guess."),
    ("Isaac Newton", "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things."),
    ("Isaac Newton", "What we know is a drop, what we do not know is an ocean."),
    ("Isaac Newton", "I can calculate the motion of heavenly bodies, but not the madness of people."),
    ("Niels Bohr", "An expert is a person who has made all the mistakes that can be made in a very narrow field."),
    ("Niels Bohr", "The opposite of a correct statement is a false statement. But the opposite of a profound truth may well be another profound truth."),
    ("Galileo Galilei", "All truths are easy to understand once they are discovered; the point is to discover them."),
    ("Galileo Galilei", "In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual."),
    ("Galileo Galilei", "Measure what is measurable, and make measurable what is not so."),
    ("Carl Sagan", "Science is a way of thinking much more than it is a body of knowledge."),
    ("Carl Sagan", "We are a way for the cosmos to know itself."),
    ("Richard Feynman", "I would rather have questions that cannot be answered than answers that cannot be questioned."),
    ("Richard Feynman", "Physics is like sex: sure, it may give some practical results, but that is not why we do it."),
    ("Richard Feynman", "The imagination of nature is far, far greater than the imagination of man."),
    ("Thomas Henry Huxley", "The great tragedy of science — the slaying of a beautiful hypothesis by an ugly fact."),
    ("Thomas Henry Huxley", "Try to learn something about everything and everything about something."),
    ("Isaac Asimov", "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom."),
    ("Isaac Asimov", "Self-education is, I firmly believe, the only kind of education there is."),
    ("Immanuel Kant", "Two things awe me most, the starry sky above me and the moral law within me."),
    ("John von Neumann", "In mathematics you don't understand things. You just get used to them."),
    ("Andrew Wiles", "The definition of a good mathematical problem is the mathematics it generates rather than the problem itself."),
    ("William Paul Thurston", "Mathematics is not about numbers, equations, or algorithms: it is about understanding."),
    ("Benjamin Franklin", "Tell me and I forget. Teach me and I remember. Involve me and I learn."),
    ("Benjamin Franklin", "An investment in knowledge pays the best interest."),
    ("Benjamin Franklin", "Energy and persistence conquer all things."),
    ("Marie Curie", "We must have perseverance and above all confidence in ourselves."),
    ("Marie Curie", "I was taught that the way of progress was neither swift nor easy."),
    ("Louis Pasteur", "Chance favors the prepared mind."),
    ("Louis Pasteur", "Science knows no country, because knowledge belongs to humanity."),
    ("Charles Darwin", "It is not the strongest of the species that survives, nor the most intelligent. It is the one most adaptable to change."),
    ("Nikola Tesla", "The day science begins to study non-physical phenomena, it will make more progress in one decade than in all the previous centuries."),
    ("Nikola Tesla", "If you want to find the secrets of the universe, think in terms of energy, frequency and vibration."),
    ("Ada Lovelace", "Imagination is the Discovering Faculty, pre-eminently. It is that which penetrates into the unseen worlds around us."),

    # ── Proverbs ────────────────────────────────────────────────────
    ("Japanese Proverb", "Fall seven times, stand up eight."),
    ("Chinese Proverb", "The best time to plant a tree was twenty years ago. The second best time is now."),
    ("Lao Tzu", "A journey of a thousand miles begins with a single step."),
    ("Confucius", "It does not matter how slowly you go as long as you do not stop."),
    ("Confucius", "Our greatest glory is not in never falling, but in rising every time we fall."),
    ("Confucius", "The man who moves a mountain begins by carrying away small stones."),
    ("Aristotle", "We are what we repeatedly do. Excellence, then, is not an act, but a habit."),
    ("Aristotle", "The roots of education are bitter, but the fruit is sweet."),
    ("Seneca", "Luck is what happens when preparation meets opportunity."),
    ("Plato", "Necessity is the mother of invention."),
    ("African Proverb", "If you want to go fast, go alone. If you want to go far, go together."),
    ("English Proverb", "Where there is a will, there is a way."),
    ("Winston Churchill", "Success is not final, failure is not fatal: it is the courage to continue that counts."),
    ("Winston Churchill", "If you are going through hell, keep going."),
    ("Nelson Mandela", "It always seems impossible until it is done."),
]
